/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_googleresearch_capturesync_wrapperJNI */

#ifndef _Included_com_googleresearch_capturesync_wrapperJNI
#define _Included_com_googleresearch_capturesync_wrapperJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_googleresearch_capturesync_wrapperJNI
 * Method:    sendData
 * Signature: ([B)F
 */
JNIEXPORT jfloat JNICALL Java_com_googleresearch_capturesync_wrapperJNI_sendData
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
