name: Android CI on Ubuntu and MacOS

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Update CMake version
        run: echo "yes" | $ANDROID_HOME/tools/bin/sdkmanager "cmake;3.18.1" --channel=3

      - name: Update ndk-version
        run: echo "yes" | $ANDROID_HOME/tools/bin/sdkmanager --install "ndk;22.1.7171670"

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run unit tests
        run: ./gradlew test

      - name: Run android tests
        if: matrix.os == 'macos-latest'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 23
          target: default
          arch: x86
          ndk: 22.1.7171670
          cmake: 3.18.1
          script: ./gradlew connectedCheck
